os: linux

language: go

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.5/hugo_0.55.5_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - git clone https://github.com/gohugoio/hugoBasicExample.git
  - git clone https://github.com/jdahm/azure.git themes/azure

script:
  - cd hugoBasicExample
  - hugo

# deploy:
#   local_dir: public # Default static site output dir for Hugo
#   repo: <yourusername>/<yourusername>.github.io # This is the slug of the repo you want to deploy your site to
#   target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
#   provider: pages
#   skip_cleanup: true
