language: go

go:
  - master # This uses automatically the latest version of go

before_install:
  - sudo apt-get install -y hugo
  - git clone https://github.com/gohugoio/hugoBasicExample.git
  - cd hugoBasicExample/themes

script:
  - cd ../../
  - hugo # This commands builds your website on travis

# deploy:
#   local_dir: public # Default static site output dir for Hugo
#   repo: <yourusername>/<yourusername>.github.io # This is the slug of the repo you want to deploy your site to
#   target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
#   provider: pages
#   skip_cleanup: true
