name = "Lapis"
license = "MIT"
licenselink = "https://github.com/jdahm/lapis/blob/master/LICENSE"
description = "A light and minimalist theme for Hugo"
homepage = "https://github.com/jdahm/lapis"
tags = [ "minimal", "simple", "clean", "personal", "blog" ]
features = [ "blog", "single-column" ]
min_version = "0.43"

[author]
    name = "Johann Dahm"
    homepage = "http://jdahm.me"

[original]
    name = "Indigo"
    homepage = "http://koppl.in/indigo"
    repo = "https://github.com/sergiokopplin/indigo"
