Copyright = "2019 John Doe - All Rights Reserved"
Title = "John Doe's personal site"
Description = "John Doe's personal site"

[Author]
    name = "John Doe"
    bio = "A man who travels the world eating noodles"
    avatar = "/profile.jpg"

[params]
    keywords = [ "personal-site", "programming" ]
    skip_footer = true
    skip_nav = true
    animate = true
    star = false

    [[params.social]]
        icon = "twitter"
        url = "https://twitter.com/mytwitter"
        name = "Twitter"

    [[params.social]]
        icon = "github"
        url = "https://github.com/mygithub"
        name = "GitHub"

    [[params.social]]
        icon = "medium"
        url = "https://medium.com/@medium"

    [[params.social]]
        icon = "mail"
        url = "myemail@gmail.com"

[menu]
    [[menu.main]]
        name = "Blog"
        url = "blog"

    [[menu.main]]
        name = "About"
        url = "about"
