baseURL = "www.example.com"
title = "John Doe"

theme = "azure"

[Author]
    name = "John Doe"
    bio = "A man who travels the world eating noodles"
    avatar = "profile.jpg"

[params]
    description = "John Doe's personal site"
    keywords = [ "personal-site", "programming" ]
    animate = true
    width = "large"

[[params.social]]
    icon = "facebook"
    url = "https://facebook.com/myfacebook"

[[params.social]]
    icon = "twitter"
    url = "https://twitter.com/mytwitter"

[[params.social]]
    icon = "github"
    url = "https://github.com/mygithub"

[[params.social]]
    icon = "medium"
    url = "https://medium.com/@medium"

[[params.social]]
    icon = "mail"
    url = "myemail@gmail.com"

# [[params.nav]]
#     name = "Blog"
#     url = "blog/"

[[params.nav]]
    name = "Projects"
    url = "projects/"

[[params.nav]]
    name = "About"
    url = "about/"

[[params.nav]]
    name = "Résumé"
    url = "https://google.com/?q=my+resume"
